name: Merge

on:
  schedule: # Run every 3 hours
  - cron: "0 0,3,6,9,12,15,18,21 * * *"
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge main into production
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch --unshallow
          git pull origin main
          git checkout production
          git pull origin production
          git merge main --no-ff --no-edit
          git push origin production
